// Global
const actions = {

  // Global
  MESSAGE_ADD: 'conveyor/global/MESSAGE_ADD',
  MESSAGE_REMOVE: 'conveyor/global/MESSAGE_REMOVE',
  MESSAGE_REMOVE_ALL: 'conveyor/global/MESSAGE_REMOVE_ALL',

  // Source
  SOURCE_LOAD_BY_NAME: 'conveyor/global/SOURCE_LOAD_BY_NAME',
  SOURCE_LOAD_BY_NAME_SUCCESS: 'conveyor/global/SOURCE_LOAD_BY_NAME_SUCCESS',
  SOURCE_LOAD_BY_NAME_FAIL: 'conveyor/global/SOURCE_LOAD_BY_NAME_FAIL',

  SOURCE_LOAD_ALL: 'conveyor/global/SOURCE_LOAD_ALL',
  SOURCE_LOAD_ALL_SUCCESS: 'conveyor/global/SOURCE_LOAD_ALL_SUCCESS',
  SOURCE_LOAD_ALL_FAIL: 'conveyor/global/SOURCE_LOAD_ALL_FAIL',

  SOURCE_LOAD_NEXT_PAGE: 'conveyor/global/SOURCE_LOAD_NEXT_PAGE',
  SOURCE_LOAD_NEXT_PAGE_SUCCESS: 'conveyor/global/SOURCE_LOAD_NEXT_PAGE_SUCCESS',
  SOURCE_LOAD_NEXT_PAGE_FAIL: 'conveyor/global/SOURCE_LOAD_NEXT_PAGE_FAIL',

  SOURCE_CLEAR_SELECTED: 'conveyor/global/SOURCE_CLEAR_SELECTED',
  SOURCE_CLEAR_ALL: 'conveyor/global/SOURCE_CLEAR_ALL',

  //Channels
  CHANNEL_LOAD_ALL: 'conveyor/global/CHANNEL_LOAD_ALL',
  CHANNEL_LOAD_ALL_SUCCESS: 'conveyor/global/CHANNEL_LOAD_ALL_SUCCESS',
  CHANNEL_LOAD_ALL_FAIL: 'conveyor/global/CHANNEL_LOAD_ALL_FAIL',

  CHANNEL_CREATE: 'conveyor/global/CHANNEL_CREATE',
  CHANNEL_CREATE_SUCCESS: 'conveyor/global/CHANNEL_CREATE_SUCCESS',
  CHANNEL_CREATE_FAIL: 'conveyor/global/CHANNEL_CREATE_FAIL',

  CHANNEL_DELETE: 'conveyor/global/CHANNEL_DELETE',
  CHANNEL_DELETE_SUCCESS: 'conveyor/global/CHANNEL_DELETE_SUCCESS',
  CHANNEL_DELETE_FAIL: 'conveyor/global/CHANNEL_DELETE_FAIL',

  CHANNEL_CLEAR_SELECTED: 'conveyor/global/CHANNEL_CLEAR_SELECTED',
  CHANNEL_CLEAR_ALL: 'conveyor/global/CHANNEL_CLEAR_ALL',

  CHANNEL_UPLOAD: 'conveyor/global/CHANNEL_UPLOAD',
  CHANNEL_UPLOAD_SUCCESS: 'conveyor/global/CHANNEL_UPLOAD_SUCCESS',
  CHANNEL_UPLOAD_FAIL: 'conveyor/global/CHANNEL_UPLOAD_FAIL',

  //Settings
  SETTINGS_LOAD_ALL: 'conveyor/global/SETTINGS_LOAD_ALL',
  SETTINGS_LOAD_ALL_SUCCESS: 'conveyor/global/SETTINGS_LOAD_ALL_SUCCESS',
  SETTINGS_LOAD_ALL_FAIL: 'conveyor/global/SETTINGS_LOAD_ALL_FAIL',

  SETTINGS_UPDATE: 'conveyor/global/SETTINGS_UPDATE',
  SETTINGS_UPDATE_SUCCESS: 'conveyor/global/SETTINGS_UPDATE_SUCCESS',
  SETTINGS_UPDATE_FAIL: 'conveyor/global/SETTINGS_UPDATE_FAIL',

};
export default actions;
