version: '3.0'

services:
  node-red:
    image: nodered/node-red-docker
    ports: ['1880:1880']
    networks: ['ingest-net']
  elasticsearch:
    build: elasticsearch/
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    ports: ['9200:9200']
    networks: ['ingest-net']
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA:-./es-data}:/usr/share/elasticsearch/data
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', '${ES_USER:-elastic}:${ES_PASSWORD:-changeme}', 'http://localhost:9200']
      interval: 1m30s
      timeout: 10s
      retries: 3
  kibana:
    build: kibana/
    ports: ['5601:5601']
    networks: ['ingest-net']
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    depends_on:
      - elasticsearch
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601/login']
      interval: 1m30s
      timeout: 10s
      retries: 3
networks:
  ingest-net:
